"""empty message

Revision ID: 4c0b3581909c
Revises: fe27fdae03a1
Create Date: 2023-12-17 01:50:42.034208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c0b3581909c'
down_revision = 'fe27fdae03a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa_presensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nim_id', sa.Integer(), nullable=False))
        batch_op.drop_index('nama')
        batch_op.drop_index('nim')
        batch_op.create_foreign_key(None, 'user', ['nim_id'], ['id'])
        batch_op.drop_column('nim')
        batch_op.drop_column('nama')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa_presensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', mysql.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('nim', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('nim', ['nim'], unique=False)
        batch_op.create_index('nama', ['nama'], unique=False)
        batch_op.drop_column('nim_id')

    # ### end Alembic commands ###
