"""empty message

Revision ID: cb635579bc1c
Revises: 
Create Date: 2023-12-18 06:36:28.843081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb635579bc1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=80), nullable=False),
    sa.Column('nama', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama'),
    sa.UniqueConstraint('nim')
    )
    op.create_table('presensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prodi', sa.String(length=60), nullable=False),
    sa.Column('matakuliah', sa.String(length=60), nullable=False),
    sa.Column('kelas', sa.String(length=60), nullable=False),
    sa.Column('tanggal', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mahasiswa_presensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim_id', sa.Integer(), nullable=False),
    sa.Column('presensi_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nim_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['presensi_id'], ['presensi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mahasiswa_presensi')
    op.drop_table('presensi')
    op.drop_table('user')
    # ### end Alembic commands ###
